export {default as ChartSlice} from './ChartSlice'
export {default as CoinSlice} from './CoinSlice'
export {default as DropSlice} from './DropSlice'
export {default as ThemeSlice} from './ThemeSlice'
export {default as AlertSlice} from './AlertSlice'
export {default as PieItemSlice} from './PieItemSlice'
export {default as PhoneSlice} from "./PhoneSlice";
export {default as RecentSlice} from "./RecentSlice";
export {default as WatchSlice} from "./WatchSlice";